#!/usr/bin/env zsh
. ./common_functions

package_dependencies="gnome-desktop gvim ack arandr ctags curl dmenu downgrade dnsutils dropbox flashplugin gimp ghc htop imagemagick keepassx libmysqlclient mysql libxslt libxml2 make mlocate nautilus ncurses ntfs-3g parallel pm-utils rabbitmq qt4 qtwebkit redis rsync ruby screen tmux scrot rxvt-unicode sed siege apache sqlite terminus-font unrar unzip vlc wget whois wicd xclip xmobar xmonad xmonad-contrib xscreensaver zip" 

fancy_echo "Installing git, for source control management ..."
  successfully install_packages git xclip firefox

fancy_echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

fancy_echo "Installing oh-my-zsh for the win ..."
  [[ -d ~/.oh-my-zsh ]] || successfully git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
  notice "After install you can configure oh_my_zsh in your .zshrc file"

fancy_echo "Installing google-chrome-beta"
  successfully install_packages google-chrome-beta

fancy_echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | xclip -selection clipboard
  successfully google-chrome https://github.com/account/ssh

fancy_echo "Installing core dependencies ..."
  successfully install_packages $package_dependencies

fancy_echo "Installing rvm for changing Ruby Versions ..."
  successfully \curl -L https://get.rvm.io | bash -s stable --autolibs=3 --ruby
  successfully rvm reload

fancy_echo "Installing Ruby Enterprise Edition ..."
  successfully install_ruby ree

fancy_echo "Installing Ruby 1.9.3 ..."
  successfully install_ruby 1.9.3 --patch railsexpress

fancy_echo "Installing Ruby 2.0 ..."
  successfully install_ruby 2.0

fancy_echo "Setting 1.9.3 as the default"
  successfully rvm use 1.9.3 --default

fancy_echo "Update to latest Rubygems version ..."
  successfully gem update --system

notice "You should consult with the senior devs to get vim configured"
